[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
mock-pyth-pull = "F3iMe36nLLYH9gG7WVsV3eSmSZZavy4bSkA4ra13qeDx"
mock-pyth-push = "HxWaRfGzPvrFPz1UzRBEvmsK9LxK65r8Jtt195NDbg7j"
test-contract = "8jm5jnUyUc6a55qsXFTxUSjM3doH5aCfWjwYKjuEJW53"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
