[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
mock-pyth-pull = "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ"
mock-pyth-push = "FsJ3A3u2vn5cTVofAjvy6y5kwABJAqYWpe4975bi2epH"
test-contract = "8jm5jnUyUc6a55qsXFTxUSjM3doH5aCfWjwYKjuEJW53"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
